name: Publish .NET Project to Remote Server

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Publish
      run: dotnet publish -c Release --no-self-contained -o ./publish

    - name: Copy to remote server
      uses: appleboy/ssh-action@v0.19.0
      with:
        host: ${{ secrets.203.215.171.93 }}
        username: ${{ secrets.Administrator }}
        password: ${{ secrets.Helloitsbspo1! }}
        port: ${{ secrets.3389 }}
        script: |
          New-Item -ItemType Directory -Force -Path "C:\inetpub\wwwroot\myapp"
          Copy-Item -Path "./publish/*" -Destination "C:\inetpub\wwwroot\myapp" -Recurse

    - name: Remove publish folder
      run: rm -rf ./publish
